module.exports = Object.freeze ({
    IDLE : 'Idle',

    W_GET_GUPCOMMON : 'W_GET_GupCommon',
    W_GET_AN_GUPCOMMON : 'W_GET_An_GupCommon',
    W_GET_GUPCOMMON_BY_PRIVATEID : 'W_GET_GupCommon_By_PrivateId',
    W_GET_GUPGLOBALSERVICE : 'W_GET_GupGlobalService',
    W_GET_STBMANAGEDEVICEPROFILE : 'W_GET_StbManageDeviceProfile',
    W_GET_GUPDEVICE : 'W_GET_GupDevice',
    W_POST_MODIFYIDENTITY : 'W_POST_ModifyIdentity',
    W_POST_MODIFYIDENTITY_GUPDEVICE : 'W_POST_ModifyIdentity_GupDevice',
    W_DELETE_MODIFYIDENTITY_GUPDEVICE : 'W_DELETE_ModifyIdentity_GupDevice',
    W_POST_MODIFYIDENTITY_GUPIMPU : 'W_POST_ModifyIdentity_GupImpu',
    W_DELETE_MODIFYIDENTITY_GUPIMPU : 'W_DELETE_ModifyIdentity_GupImpu',
    W_POST_MODIFYIDENTITY_GUPIMPI : 'W_POST_ModifyIdentity_GupImpi',
    W_DELETE_MODIFYIDENTITY_GUPIMPI : 'W_DELETE_ModifyIdentity_GupImpi',
    W_POST_MODIFYIDENTITY_GUPSUBPROFILE : 'W_POST_ModifyIdentity_GupSubprofile',
    W_DELETE_MODIFYIDENTITY_GUPSUBPROFILE : 'W_DELETE_ModifyIdentity_GupSubProfile',
    W_DELETE_MODIFYIDENTITY : 'W_DELETE_ModifyIdentity',
    W_POST_SUBSCRIBER : 'W_POST_Subscriber',
    W_DELETE_SUBSCRIBER : 'W_DELETE_Subscriber',
    W_POST_GUPSERVICEPROFILE : 'W_POST_GupServiceProfile',
    W_DELETE_GUPSERVICEPROFILE : 'W_DELETE_GupServiceProfile',
    W_POST_GUPSERVICEELEMENT : 'W_POST_GupServiceElement',
    W_DELETE_GUPSERVICEELEMENT : 'W_DELETE_GupServiceElement',
    W_PUT_GUPSERVICEELEMENT : 'W_PUT_GupServiceElement',
    W_PUT_DELETE_GUPSERVICEELEMENT : 'W_PUT_DELETE_GupServiceElement',
    W_PUT_GUPSUBPROFILE : 'W_PUT_GupSubProfile',
    W_PUT_GUPIMPU : 'W_PUT_GupImpu',
    W_POST_GUPIMPI : 'W_POST_GupImpi',
    W_DELETE_GUPIMPI : 'W_DELETE_GupImpi',
    W_PUT_GUPIMPI : 'W_PUT_GupImpi',
    W_POST_GUPIMPU : 'W_POST_GupImpu',
    W_DELETE_GUPIMPU : 'W_DELETE_GupImpu',
    W_POST_GUPSUBPROFILE : 'W_POST_GupSubProfile',
    W_DELETE_GUPSUBPROFILE : 'W_DELETE_GupSubProfile',
    W_POST_GUPDEVICE : 'W_POST_GupDevice',
    W_DELETE_GUPDEVICE : 'W_DELETE_GupDevice',
    W_POST_GENERATEPARTNERSPECIFICPRIVATEID : 'W_POST_GeneratePartnerSpecificPrivateId',

    W_SCF_GET_DECRYPTPARTNERSPECIFIC : 'W_SCF_GET_Decryptpartnerspecific',
    W_SCF_POST_GENERATEPARTNERSPECIFICPRIVATEID : 'W_SCF_POST_GeneratepartnerspecificprivateId',

    W_THIRDPARTY_POST_THIRDPARTY : 'W_THIRDPARTY_POST_Thirdparty',

    W_SSO_IDS_POST_IDENTITYSERVICE : 'W_SSO_IDS_POST_IdentityService',
    W_SSO_IDS_GET_CUSTOMERPROFILE : 'W_SSO_IDS_GET_CustomerProfile',

    W_LDAP_POST_LDAP : 'W_LDAP_POST_Ldap',

    W_QUERY_E01_SERVICEOFPAYLOAD : 'W_QUERY_E01_SERVICEOFPAYLOAD',
    W_EXTERNAL_PUSHNOTIFICATIONINFO : 'W_EXTERNAL_PUSHNOTIFICATIONINFO',
    W_PANTRY_PUSHNOTIFICATIONINFO : 'W_EXTERNAL_PUSHNOTIFICATIONINFO',

    END : 'End',


})